version: '3.8'


services:

 identidock:
  build: .
  ports:
   - "5005:5002"
  environment:
   - ENV:DEV
  volumes:
   - ./app:/app
  links:
   - dnmonster
   - redis
 dnmonster:
  image: amouat/dnmonster
 redis:
  image: redis:3.0
